name: Upload media

on:
  push:
    branches: [ main ]

jobs: 
  upload:
    runs-on: ubuntu-latest
    name: Upload media to bucket
    environment: Protected
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: AWS S3 sync
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          BUCKET: media-fh4838dscb6t5828s
          REGION: eu-west-3
        run: |
          aws s3 sync ./media/ s3://${BUCKET}/ --region ${REGION} --delete
