name: Upload media

on:
  push:
    branches: [ main, feature/dev-3181-devops-migrate-media-scaleway ]

jobs: 
  upload:
    runs-on: ubuntu-latest
    name: Upload media to bucket
    environment: Protected
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip, encrypt and send to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          BUCKET: pictures.dev.surfe.com
          DIRECTORY: dev
          REGION: eu-west-3
        run: |
          aws s3 cp ./media/ s3://${BUCKET}/ --region ${REGION} --recursive
